language: c

os:
  - osx

compiler:
  - gcc
  - clang

addons:
  apt:
    packages:
      - graphviz

before_install:
  - '[ "$TRAVIS_OS_NAME" != osx ] || brew update'
  - '[ "$TRAVIS_OS_NAME" != osx ] || brew install libxmlsec1'
  - '[ "$TRAVIS_OS_NAME" != osx ] || brew tap cartr/qt4'
  - '[ "$TRAVIS_OS_NAME" != osx ] || brew tap cartr/qt4'
  - '[ "$TRAVIS_OS_NAME" != osx ] || brew tap-pin cartr/qt4'
  - '[ "$TRAVIS_OS_NAME" != osx ] || brew install qt@4'
  - '[ "$TRAVIS_OS_NAME" == "centos" ] || yum install xmlsec-devel'
  - '[ "$TRAVIS_OS_NAME" == "centos" ] || yum install xmlsec-openssl-devel'

script:
  - mkdir build 
  - cd build
  - cmake ../
  - make 

matrix:
  include:
    - os: centos 
      dist: 6
      pack: rpm 
      sudo: required
    - os: osx
      osx_image: xcode7.2

notification:
  email: false
