language: c

os:
  - osx

compiler:
  - gcc
  - clang

addons:
  apt:
    packages:
      - graphviz

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      brew update
      brew install libxmlsec1
      brew tap cartr/qt4
      brew tap-pin cartr/qt4
      brew install qt@4
    ; fi
  - if [[ "$TRAVIS_OS_NAME" == "centos" ]]; then
      yum install xmlsec-devel
      yum install xmlsec-openssl-devel
    ; fi

script:
  - mkdir build 
  - cd build
  - cmake ../
  - make 

matrix:
  include:
    - os: centos 
      dist: 6
      pack: rpm 
      sudo: required
    - os: osx
      osx_image: xcode7.2

notification:
  email: false
